### ISSUE TITLE
Playit.GG connection not working

### ISSUE THREAD

**Issue by N0THSA** [enuf96/novetus-masterserver#1]
`--> !!IMPORTANT!! required for PLAYIT.gg. Change respective variables below:
local PLAYIT_ENABLED = true
local PLAYIT_ADDR = "180.ip.ply.gg"
local PLAYIT_PORT = 45065`

Playit info is correct and I am receiving connection requests

`--> Custom master server by enuf
local masterServerAddr = "127.0.0.1:5000"
local ServerName = "BRICKLINE | %MAP% | %CLIENT%"
--> Note: %MAP% and %CLIENT% are variables and will automatically get replaced by the client and map name.`

Masterserver changed to my local computer (where I'm hosting)

`127.0.0.1 - - [12/Nov/2022 18:53:31] "GET /server/keepAlive61?id=kxkrkrxrgpnuwhkbojcowccczenavtxrlkbcsvpbmseqtragvd&client=2011M&map=2011%20-%20Natural%20disasters%20survival.rbxl&name=Novetus%20|%20%MAP%%20|%20%CLIENT%&players=0/12&playitIP=180.ip.ply.gg&port=45065 HTTP/1.1" 400 -`

Output when ran

The server runs fine when PLAYIT_ENABLED = false. My ISP forbids port forwarding so Playit.GG is my only option.

**Comment by ghost** [comment]
oh wow I never realised someone actually made an issue lol

I am almost 2 months late but I guess I can finally fix the playit stuff if people are still interested

**Comment by ghost** [comment]
The issue you're facing by the way, is that in my code there is a regular expression that keeps failing because initially it will only succeed if PLAYIT_ADDR is a subdomain of playit.gg, though as I've noticed playit have started shifting their domains to the new "ip.ply.gg".

https://github.com/enuf96/novetus-masterserver/blob/main/masterserver/routes/endpoint.py#L70

**Comment by N0THSA** [comment]
Thanks! I hadn't even realized this issue was still open. It works perfectly! Thank you very much.
